---
- name: Set bridge-nf-call-iptables sysctl parameter
  become: yes
  become_user: root
  sysctl:
    sysctl_file: /etc/sysctl.conf
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Set bridge-nf-call-ip6tables sysctl parameter
  become: yes
  become_user: root
  sysctl:
    sysctl_file: /etc/sysctl.conf
    name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Set net.ipv4.ip_forward sysctl parameter
  become: yes
  become_user: root
  sysctl:
    sysctl_file: /etc/sysctl.conf
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
