---
- include_tasks: network.yml
  tags:
    - network

- include_tasks: create_user.yml
  tags:
    - user

- include_tasks: install.yml
  tags:
    - install

- include_tasks: configure_sysctl.yml
  tags:
    - sysctl

- include_tasks: start.yml
  tags:
    - start

