---
- name: Create Initialization Config
  become: yes
  become_user: root
  template:
    src: kubeadm_init.yaml.j2
    dest: /etc/kubernetes/kubeadm_init.yaml
  tags:
    - initialize  

- name: Initialize kubernetes cluster
  become: yes
  become_user: root
  shell: >
    kubeadm init
    --config=/etc/kubernetes/kubeadm_init.yaml
    --upload-certs
    --ignore-preflight-errors=NumCPU,Mem
  args:
    creates: /etc/kubernetes/manifests/kube-controller-manager.yaml 

- name: Create .kube directory
  become: yes
  become_user: "{{ kubernetes_admin_user }}"
  file:
    name: ~{{ kubernetes_admin_user}}/.kube
    state: directory
  tags:
    - initialize  

- name: Copy config file
  become: yes
  become_user: root
  command: cp -i /etc/kubernetes/admin.conf ~{{ kubernetes_admin_user }}/.kube/config
  args:
    creates: ~{{ kubernetes_admin_user}}/.kube/config 
  tags:
    - initialize  

- name: Set config file ownership
  become: yes
  become_user: root
  file:
    path: ~{{ kubernetes_admin_user }}/.kube/config
    owner: "{{ kubernetes_admin_user }}"
    group: "{{ kubernetes_admin_group }}"
    state: file
  tags:
    - initialize  
