all:
  children:
    kubernetes_masters:
      hosts:
        aws-master:
          hostname: aws-master.costa.lab
          ip_address: 10.0.1.10
          ec2_dns_name: ip-10-0-1-10.us-east-2.compute.internal
    kubernetes_nodes:
      hosts:
        aws-worker:
          hostname: aws-worker.costa.lab
          ip_address: 10.0.1.11
          ec2_dns_name: ip-10-0-1-11.us-east-2.compute.internal
  vars:
    kubernetes_master: aws-master.costa.lab
    kubernetes_version: 1.23.1-0
    kubernetes_admin_user: kubeadm
